import {appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';
import type {Analysis} from './analysisSchema';
import type {ParsedAlert} from '../parseAlert';
import type {AlertStatus} from '../state/stateMachine';

/**
 * Writes what happened back into the brain, so the next job starts where this one
 * finished.
 *
 * The incident record is generated by code, not by a model: it is a statement of
 * fact about a job that just ran, and a model paraphrasing it could only make it
 * less true. A model is used for one thing only — proposing a *generalisation* —
 * and that goes to `candidates.md`, which needs two sightings before it becomes
 * something the agent is told.
 *
 * Same discipline as `brain.py`: a candidate is never auto-promoted into trusted
 * knowledge.
 */

export interface IncidentInput {
  fingerprint: string;
  alert: ParsedAlert;
  repo: string;
  status: AlertStatus;
  attempt: number;
  analysis: Analysis | undefined;
  rounds: number;
  costUsd: number;
  mrUrl: string | undefined;
  branch: string | undefined;
  fixSha: string | undefined;
  diffStat: string | undefined;
  smokeLine: string | undefined;
  outcome: string;
  dateIso: string;
  threadTs: string | undefined;
}

/**
 * The `fingerprint:` / `service:` / `message:` header is what `brainSlice` matches
 * on when it decides whether a past incident is relevant to a new alert.
 */
export function renderIncident(input: IncidentInput): string {
  const a = input.analysis;
  const lines: string[] = [
    `fingerprint: ${input.fingerprint}`,
    `service: ${input.alert.service ?? 'unknown'}`,
    `message: ${input.alert.message.split('\n')[0]!.slice(0, 300)}`,
    `app: ${input.alert.appName}`,
    `repo: ${input.repo}`,
    `date: ${input.dateIso}`,
    `status: ${input.status}`,
    `attempt: ${input.attempt}`,
    '',
    `# ${input.alert.appName} · ${input.alert.service ?? 'unknown'} · ${input.fingerprint}`,
    '',
    `**Outcome.** ${input.outcome}`,
    ''
  ];

  if (a) {
    lines.push(
      `**Root cause.** ${a.rootCause}`,
      '',
      `**Mechanism.** ${a.mechanism}`,
      '',
      `Confidence: \`${a.confidence}\`${a.isInfra ? ' · infra class, not auto-fixed' : ''}`,
      '',
      '## Code',
      ...a.citations.map(c => `- \`${c.file}:${c.line}\` — ${c.why}`),
      '',
      '## Evidence',
      ...a.evidence.map(e => `- ${e.matched} matching entries: \`${e.logQuery}\``),
      ''
    );
  } else {
    lines.push('No analysis survived verification.', '');
  }

  lines.push('## Job', `- analyze rounds: ${input.rounds}`, `- cost: $${input.costUsd.toFixed(2)}`);
  if (input.branch) lines.push(`- branch: \`${input.branch}\``);
  if (input.fixSha) lines.push(`- fix commit: \`${input.fixSha}\``);
  if (input.mrUrl) lines.push(`- MR: ${input.mrUrl}`);
  if (input.smokeLine) lines.push(`- tests: ${input.smokeLine}`);
  if (input.diffStat) lines.push('', '```', input.diffStat.trim(), '```');
  lines.push(
    '',
    '## Verdict',
    '',
    '_Filled in by hand once the MR is reviewed. A rejected fix recorded here is what stops the',
    'next job proposing it again._'
  );

  return lines.join('\n') + '\n';
}

export function indexLine(input: IncidentInput): string {
  const cause = input.analysis?.rootCause.replace(/\s+/g, ' ').slice(0, 110) ?? 'no verified cause';
  const mr = input.mrUrl ?? '—';
  return `- \`${input.fingerprint}\` · ${input.dateIso.slice(0, 10)} · ${input.alert.appName} · ${
    input.alert.service ?? '?'
  } · ${cause} · ${mr} · ${input.status}`;
}

export interface LearnDeps {
  brainRoot: string;
  log?: (line: string) => void;
}

export interface LearnResult {
  incidentPath: string;
  indexUpdated: boolean;
}

const INDEX_MARKER = '<!-- LEARN appends below this line -->';

export function writeIncident(deps: LearnDeps, input: IncidentInput): LearnResult {
  const dir = join(deps.brainRoot, 'incidents');
  mkdirSync(dir, {recursive: true});
  const incidentPath = join(dir, `${input.fingerprint}.md`);

  // A repeat job on the same fingerprint replaces the record rather than appending
  // a second one: brainSlice loads exactly one incident file per fingerprint.
  writeFileSync(incidentPath, renderIncident(input), 'utf8');

  const indexPath = join(deps.brainRoot, 'index.md');
  let indexUpdated = false;
  if (existsSync(indexPath)) {
    const current = readFileSync(indexPath, 'utf8');
    const line = indexLine(input);
    const already = new RegExp(`^- \`${input.fingerprint}\``, 'm').test(current);
    if (already) {
      // Rewrite the existing line in place, keeping the index one line per fingerprint.
      const next = current.replace(new RegExp(`^- \`${input.fingerprint}\`.*$`, 'm'), line);
      writeFileSync(indexPath, next, 'utf8');
    } else if (current.includes(INDEX_MARKER)) {
      writeFileSync(indexPath, current.replace(INDEX_MARKER, `${INDEX_MARKER}\n${line}`), 'utf8');
    } else {
      appendFileSync(indexPath, `\n${line}\n`, 'utf8');
    }
    indexUpdated = true;
  }

  return {incidentPath, indexUpdated};
}

export interface Candidate {
  app: string;
  claim: string;
  fingerprints: string[];
  seen: number;
}

const CANDIDATE_MARKER = '<!-- LEARN appends below this line -->';

export function parseCandidates(text: string): Candidate[] {
  const out: Candidate[] = [];
  for (const line of text.split('\n')) {
    const m = /^- (\d+) · ([A-Z0-9-]+) · seen (\d+) · \[([^\]]*)\] · (.+)$/.exec(line.trim());
    if (m) {
      out.push({
        app: m[2]!,
        seen: Number(m[3]),
        fingerprints: m[4]!.split(',').map(s => s.trim()).filter(Boolean),
        claim: m[5]!.trim()
      });
    }
  }
  return out;
}

function renderCandidates(candidates: Candidate[]): string {
  return candidates
    .map((c, i) => `- ${i + 1} · ${c.app} · seen ${c.seen} · [${c.fingerprints.join(', ')}] · ${c.claim}`)
    .join('\n');
}

/** Same claim from a *different* fingerprint is what raises the count. */
function sameClaim(a: string, b: string): boolean {
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
  return norm(a) === norm(b);
}

export interface RecordCandidateResult {
  seen: number;
  readyToPromote: boolean;
}

export function recordCandidate(
  deps: LearnDeps,
  input: {app: string; claim: string; fingerprint: string}
): RecordCandidateResult {
  const path = join(deps.brainRoot, 'candidates.md');
  const header = existsSync(path) ? readFileSync(path, 'utf8') : `# Candidates\n\n${CANDIDATE_MARKER}\n`;
  const candidates = parseCandidates(header);
  const existing = candidates.find(c => c.app === input.app && sameClaim(c.claim, input.claim));

  if (existing) {
    if (!existing.fingerprints.includes(input.fingerprint)) {
      existing.fingerprints.push(input.fingerprint);
      existing.seen = existing.fingerprints.length;
    }
  } else {
    candidates.push({app: input.app, claim: input.claim, fingerprints: [input.fingerprint], seen: 1});
  }

  const body = header.split(CANDIDATE_MARKER)[0] ?? '';
  writeFileSync(path, `${body}${CANDIDATE_MARKER}\n${renderCandidates(candidates)}\n`, 'utf8');

  const updated = candidates.find(c => c.app === input.app && sameClaim(c.claim, input.claim))!;
  return {seen: updated.seen, readyToPromote: updated.seen >= 2};
}
